### ISSUE TITLE
On a DOIT with PCM5021A connected according to DAC wiring diagram, the serial monitor is showing different pinout by default. 

### ISSUE THREAD

**Issue by 01GOD** [marcel-licence/esp32_drum_computer#13]
Thanks for posting that project! It sounds nice! Hoping that gets merged with one of the synths into a full groove box kinda thing with FFT ducking or amplitude based ducking. 

Anyway, notifying of a difference in the automatic DAC pinouts on the basic_synth and this project. The basic_synth played a tone through DAC after uncommented the test tone line. So tried this project after that. Here is what the serial monitor showed: 

Loading data
Firmware started successfully
I2S configured using following pins:
    BCLK,BCK: 32
    WCLK,LCK: 25
    DOUT: 33
    DIN: -1

**Comment by 01GOD** [comment]
Update: So I rewired it and it is functioning. Recommend making the pinouts same on both the drum computer and synth by default. 

For such nice sounding projects, it's a little silly that the metronome and test tone are the main options initially on basic_synth and this project, when both are capable of so much more. Recommendable to make a single line uncommentable: "awesome 4 on the floor drum sequence" define line in the drum computer project. Also a "awesome synth lead sequence" line in the basic_synth is recommendable. 

That way there can be more of a "Wow!" factor right after getting it all wired up and functioning. 

Thanks again for posting these nice projects and tutorials!

**Comment by marcel-licence** [comment]
I am happy to hear that it works. That is a good point to keep to configuration the same. I see in the config.h is a different board via a MACRO selected (BOARD_ML_V1, BOARD_ESP32_DOIT). That cause the different configuration. 
In some projects you will find "MIDI_STREAM_PLAYER_ENABLED" in config.h to playback a MIDI file from LittleFS:
- https://github.com/marcel-licence/ml_synth_pwm_osc_example
- https://github.com/marcel-licence/ml_epiano_example
- and more
There is no ESP32 in the name but they use the features (2x cores) =)

**Comment by 01GOD** [comment]
Thanks for explaining!
