### ISSUE TITLE
LittleFS

### ISSUE THREAD

**Issue by MichaelPNolan** [marcel-licence/esp32_drum_computer#4]
I am having some compile issues and I seemed to have had to rename LITTLEFS to LittleFS

```
[(https://github.com/lorol/LITTLEFS
#ths-library-is-now-part-of-arduino-esp32-core-v2)LittleFS_esp32
This library is now part of [Arduino esp32 core v2](https://github.com/espressif/arduino-esp32/tree/master/libraries/LittleFS)
Note, there it is renamed from LITTLEFS to LittleFS,
```

Manjaro update broke my python for arduino but ... another story.
PS: I got it to compile after replacing various instances of LITTLEFS with LittleFS - suggest perhaps a code update.

**Comment by marcel-licence** [comment]
Thank you for your input. I will check the latest ESP32 library. I would describe it as a feature request. In that case I might risk breaking my projects. It would be nice to know if there is any define I could check during compilation to identify the current version of the ESP32 board library I am using.

**Comment by marcel-licence** [comment]
For some reason I do not see any newer version than 1.0.6:
![grafik](https://user-images.githubusercontent.com/65245426/162575602-671d9e86-4b64-4711-bc14-9e6e55fa52cc.png)
(Arduino 1.8.13)

**Comment by MichaelPNolan** [comment]
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

My setting "Additional Boards Manager URLs" gives esp32 v2 and others

**Comment by marcel-licence** [comment]
Thank you. Yours is the dev link. I will try the release link because the dev version can show some unwanted issues because it will be continuously under development.

**Comment by marcel-licence** [comment]
I've started to use the latest esp32 board lib. How did you fix the I2S errors?

i2s_types.h:87:31: error: expected '}' before '__attribute__'
     I2S_COMM_FORMAT_I2S       __attribute__((deprecated)) = 0x01, /*!< I2S communication format I2S, correspond to `I2S_COMM_FORMAT_STAND_I2S`*/

**Comment by MichaelPNolan** [comment]
Ok - on email at first I wasn't sure what you were looking at - its this issue I started. Sorry.
So I have have the esp32_audio_kit_module
added to my project - i'm using an audio_kit that has the ac101
It compiled and worked. On this computer, indeed I do have esp32 2.0.2 and the dev link .
That was all I had to do
I defined the board like this
```
`//#define BOARD_ML_V1 /* activate this when using the ML PCB V1 */
#define BOARD_ESP32_AUDIO_KIT_AC101 /* activate this when using the ESP32 Audio Kit v2.2 with the AC101 codec */
//#define BOARD_ESP32_AUDIO_KIT_ES8388 /* activate this when using the ESP32 Audio Kit v2.2 with the ES8388 codec */
//#define BOARD_ESP32_DOIT /* activate this when using the DOIT ESP32 DEVKIT V1 board */`
```

and Midi
```
#define MIDI_PORT2_ACTIVE
#define MIDI_RX2_PIN 21 /* U2RRXD */
```

It starts up with a metronome/click going ... i haven't set up samples on the sd card or anything yet. Been distracted making a kind of saturation/distortion analogue processor to play with the organ (op amps, diode feedback to clip/soft clip).

**Comment by marcel-licence** [comment]
I tried version 2.0.3. I was not able to compile the I2S example. I will try to go back to 2.0.2. Hope this will work. Maybe I got the latest git version because I used git clone etc. (manual installation). I have no other choice otherwise I will risk that I cannot build all my projects anymore.

**Comment by MichaelPNolan** [comment]
I didn't experience this I2S bug and I've been compiling several of your products as my main work most of the year running on 2.0.2

https://github.com/Moddable-OpenSource/moddable/commit/624057e204c1556a90fddf5acfdf5c036f8a6951

I see some references to changes of the deprecated attribute there like you replace it with I2S_COMM_FORMAT_STAND_I2S

**Comment by marcel-licence** [comment]
I've now updated the code and fixed the shown issues. Please feel free to check out and provide feedback. The code is now designed to support version 1.0.6 and version 2.0.2.

It looks like that the design of the arduino esp32 board may change soon. The deprecated messages are indicators that code should be updated to ensure compatibility in future. I am updating my projects today.

**Comment by marcel-licence** [comment]
This issue should be fixed with my last push. Please let me know if that also works for you
