### ISSUE TITLE
Codec failure Error

### ISSUE THREAD

**Issue by mattia714** [marcel-licence/esp32_drum_computer#9]
Hi,
I have an Audio Kit with ES8388 codec.
I uploaded data with littlefs then I compiled and uploaded the code with no errors, but after reset I got:
rst:0x1 (POWERON_RESET),boot:0x1f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4

Loading data
Initialize Audio Interface
Connect to ES8388 codec... 0x00: 0x00
0x01: 0x00
Failed!
0x00: 0x00
0x01: 0x00
Failed!
0x00: 0x00
0x01: 0x00
Failed!

DIP Switches : OFF, ON, ON, OFF, OFF

Compiling settings as following image:

![compile](https://user-images.githubusercontent.com/78443333/174153608-b6cc10ad-9c9d-4f34-ac29-60ae40c6aab1.jpg)

I tried also "ml_synth_organ_example" with same results.

Any ideas?

Thanks in advance.

**Comment by mattia714** [comment]
Solved!
In board_audio_kit_es8388.h file of ,l_synthtools library I changed
#define ES8388_CFG_I2C  1
with
#define ES8388_CFG_I2C  2

(but i still not hear the metronome when the board starts)

**Comment by marcel-licence** [comment]
Thanks for your feedback. I guess the I2S setting should be adjusted too
